spring:
  application:
    name: potential

  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB}?serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 30000 # 30초 커넥션 대기 타임아웃
      maximum-pool-size: 50
      minimum-idle: 10
      connection-test-query: SELECT 1 # 커넥션 확인용 쿼리 선언부
      keepalive-time: 60000 # 1분 마다 상태 체크

  # Redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# JWT
jwt:
  secret:
    key: ${JWT_KEY}
    accessExpire: 1800000
    refreshExpire: 60480000
    
# PortOne
portone:
  api-secret: ${PORTONE_API_SECRET:test-api-secret}
  webhook-secret: ${PORTONE_WEBHOOK_SECRET:test-webhook-secret}

# SpringDocs With Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: info

server:
  port: 8080